baseURL = "/"
languageCode = "nb-no"
DefaultContentLanguage = "nb"

title = "Orden i eget hus - i praksis"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
#editURL = "https://github.com/arkitektum/ordeniegethus/edit/master/exampleSite/content/"
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = true # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter


[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre ="<h3>Lenker</h3>"
name = "Difi - orden i eget hus"
identifier = "ds"
url = "https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning/veileder-orden-i-eget-hus"
weight = 10

[[menu.shortcuts]]
name = "Felles datakatalog"
url = "https://fellesdatakatalog.digdir.no/"
weight = 11

[[menu.shortcuts]]
name = "Digitaliseringsstrategien - KMD"
url = "https://www.regjeringen.no/no/dokumenter/en-digital-offentlig-sektor/id2653874/sec1"
weight = 12

[[menu.shortcuts]]
name = "Nasjonalt ressurssenter for deling av data"
url = "https://www.digdir.no/digitalisering-og-samordning/nasjonalt-ressurssenter-deling-av-data/1914"
weight = 13

[[menu.shortcuts]]
name = "Dataforvaltning og deling i kommunane"
url = "https://www.regjeringen.no/no/dokumenter/dataforvaltning-og--deling-i-kommunane/id2741610/"
weight = 14
